import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create by Marbi Tech Industries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="next-express-banner">
        <h1>NEXT + EXPRESS = 🔥</h1>
      </div>
    </div>
  );
};

export default Home;
